import "./termsPage.css";
import { Link } from "react-router-dom";

const TermsPage = () => {
  return (
    <div className="termsPage">
      <div className="termsContainer">
        <h1>Terms of Service</h1>
        <p className="lastUpdated">Last updated: May 2026</p>

        <section>
          <h2>1. About ASSka AI</h2>
          <p>
            ASSka AI is an educational AI assistant designed to help students
            learn, understand concepts, solve problems, and improve their
            academic performance. This service is intended for educational
            purposes only.
          </p>
        </section>

        <section>
          <h2>2. Acceptance of Terms</h2>
          <p>
            By accessing or using ASSka AI, you agree to be bound by these
            Terms of Service. If you do not agree to these terms, please do not
            use the service.
          </p>
        </section>

        <section>
          <h2>3. Educational Use Only</h2>
          <p>
            ASSka AI is provided strictly for educational and learning purposes.
            You agree to use this service to:
          </p>
          <ul>
            <li>Ask academic questions and get explanations</li>
            <li>Get help understanding study material</li>
            <li>Solve math, science, coding, and other academic problems</li>
            <li>Improve your understanding of subjects</li>
          </ul>
          <p>
            You must not use ASSka AI to generate harmful, misleading, or
            inappropriate content.
          </p>
        </section>

        <section>
          <h2>4. User Accounts</h2>
          <p>
            You must create an account to use ASSka AI. You are responsible for
            maintaining the confidentiality of your account credentials and for
            all activities that occur under your account. You must be at least
            13 years old to create an account.
          </p>
        </section>

        <section>
          <h2>5. AI-Generated Content</h2>
          <p>
            Responses generated by ASSka AI are produced by artificial
            intelligence and may not always be accurate. Always verify important
            information with your teachers, textbooks, or other reliable
            sources. ASSka AI is a learning aid, not a replacement for proper
            education.
          </p>
        </section>

        <section>
          <h2>6. Privacy & Data</h2>
          <p>
            We collect and store your chat history to provide a better
            experience. Your data is stored securely and is not shared with
            third parties for commercial purposes. By using ASSka AI, you
            consent to the collection of this data.
          </p>
        </section>

        <section>
          <h2>7. Prohibited Conduct</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to cheat in exams or academic assessments dishonestly</li>
            <li>Upload harmful, offensive, or inappropriate content</li>
            <li>Attempt to reverse-engineer or misuse the platform</li>
            <li>Share your account with others</li>
          </ul>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>
            ASSka AI is provided "as is" without warranties of any kind. We are
            not liable for any academic outcomes, decisions made based on AI
            responses, or any indirect damages arising from the use of this
            service.
          </p>
        </section>

        <section>
          <h2>9. Changes to Terms</h2>
          <p>
            We reserve the right to update these terms at any time. Continued
            use of ASSka AI after changes constitutes acceptance of the new
            terms.
          </p>
        </section>

        <section>
          <h2>10. Contact</h2>
          <p>
            If you have any questions about these Terms of Service, please{" "}
            <Link to="/contact">contact us</Link>.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsPage;
